// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Generate(arg1:types.GenerateRequest):Promise<types.GenerateResponse>;

export function GetGlossary():Promise<Record<string, string>>;

export function GetNormalization():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function SaveGlossary(arg1:Record<string, string>):Promise<void>;

export function SaveNormalization(arg1:Record<string, string>):Promise<void>;
