// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {model} from '../models';

export function Generate(arg1:types.GenerateRequest):Promise<types.GenerateResponse>;

export function GetGlossary():Promise<model.Dictionary>;

export function GetNormalization():Promise<model.Dictionary>;

export function Greet(arg1:string):Promise<string>;

export function SaveGlossary(arg1:model.Dictionary):Promise<void>;

export function SaveNormalization(arg1:model.Dictionary):Promise<void>;
