// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {types} from '../models';

export function CheckUpdates():Promise<service.UpdateInfo>;

export function Generate(arg1:types.GenerateRequest):Promise<types.GenerateResponse>;

export function GetFailure():Promise<Record<string, service.FailureEntry>>;

export function GetGlossary():Promise<Record<string, string>>;

export function GetNormalization():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function SaveFailure(arg1:Record<string, service.FailureEntry>):Promise<void>;

export function SaveGlossary(arg1:Record<string, string>):Promise<void>;

export function SaveNormalization(arg1:Record<string, string>):Promise<void>;
