// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GetGlossary() {
  return window['go']['main']['App']['GetGlossary']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveGlossary(arg1) {
  return window['go']['main']['App']['SaveGlossary'](arg1);
}
